title: i-Sociaal Lab
description: Samen werken aan dataproducten
remote_theme: just-the-docs/just-the-docs

# Zoekbalk in de topbar
search_enabled: true

# Logo + titel in de header (1 plaatje)
logo: assets/logo.png

# Favicon met logo 
favicon_ico: assets/favicon.png

nav-footer: "© 2025 i-Sociaal Lab    "

# Bovenbalk: extra navigatie-links (rechtsboven)
aux_links:
  Ketenbureau: https://i-sociaaldomein.nl
  GitHub: https://github.com/i-Sociaal-Lab

# (optioneel) kleurmodus
color_scheme: light
